# Generated by Django 5.2 on 2025-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('create', models.DateField(auto_now_add=True)),
                ('permiso', models.BinaryField()),
            ],
        ),
    ]
